version: '3.7'

services:
   db:
     image: mysql:5.7
     volumes:
       - nordref_data:/var/lib/mysql
     ports:
       - 4306:3306
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: sql
       MYSQL_DATABASE: nordref_dev
       MYSQL_USER: root
       MYSQL_PASSWORD: sql

volumes:
    nordref_data: {}